### ISSUE TITLE
correctly set Profiling.procID

### ISSUE THREAD

**Issue by cekees** [erdc-cm/proteus#186]
The Profiling module needs to know the rank for various reasons, but instead of forcing comm initialization on import we've been allowing logging to be buffered until Comm.init() is  called. This is causing a problem running all the tests with nosetests.
https://github.com/erdc-cm/proteus/blob/master/proteus/Profiling.py#L25

**Comment by ahmadia** [comment]
See: https://github.com/erdc-cm/proteus/commit/e0d347e059ecd858577a2fa934d4369d5d887ae7 for one approach to fixing this.  It just needs to be called as a fixture on any test that is going to use logging.

**Comment by ahmadia** [comment]
And it's safe to use as a file-level fixture as well, which might be the better way to use it.

**Comment by ahmadia** [comment]
FWIW, I'm okay with either approach 

1. fixing logging so that it always ensures that Comm is initialized first when Profiling is imported
2. deferring complete logging setup until the communicator has been initialized and logging is explicitly set up

One thing I think we should do regardless is move all the communicator initialization into the Comm module file itself.  For example, the explicit preloading that uses config should happen when Comm is initialized.  The way that it's currently scattered across a few files is very confusing.

**Comment by cekees** [comment]
Agreed. I think I'm still more inclined to 2, but I haven't had much time to think this through. The specific case that we're dealing with here is "user" p/n/so input modules where  we want to encourage using Profiling.logEvent without triggering a Comm.init or forcing the user to think about parallel programming at all. The input modules get very complicated, and we really want nice  reporting about what is getting executed in them.  If you just use print statements it  creates a big mess for parallel runs though, which is the reason for encouraging the use of  logEvent.

**Comment by ahmadia** [comment]
In that case, I'd probably go with [1].  Parallel initialization is supposed to happen as soon as possible in MPI jobs anyway, so I don't know of any good reasons not to just ensure that the communicators are set up as soon as a log event is triggered.
